spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://172.16.36.30:3306/ivb_server?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8082


